### ISSUE TITLE
Store zone updates in flash memory

### ISSUE THREAD

**Issue by AntonHermann** [hex-five/multizone-iot-sdk#2]
Hey :)

is it possible to store the updated zone binaries (e.g. zone3.1, zone4.1, ..) in flash memory?

I want to implement remote software updates on a MultiZone project based on the HiFive RevB board. This board only has 16K RAM which is fully used in the [default configuration](https://github.com/hex-five/multizone-sdk/blob/master/bsp/FE310/multizone.cfg).

Even though I created a memory region in flash with `rw-` access rights, writing to that memory directly results in a _Store access fault_. Reading works perfectly fine.

Thanks in advance

**Comment by cgarlati** [comment]
Hi Anton:

Your MultiZone "rw-" setting is correct.

The "Store access fault" is probably raised by the PMA unit due to the fact that your specific hardware doesn't allow CPU writes (stores) to the memory space mapped to the flash region. Writing to flash tipically requires a specific unlock / erase / write / lock procedure, strict timing, and exclusive access to the device.

I suggest you contact the hw vendor (SiFive) to see 1) if CPU flash stores are allowed at all and  2) if they provide sample code to do it. My experience is that more often than not this is not a design requirement and therefore not supported.

Cheers

**Comment by AntonHermann** [comment]
Hi Cesare,

thank you so much for your reply and for the explanation on what I could do.
I didn't think of the PMA at all.

I'll try reaching out to SiFive.

Thanks and kind regards
